# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "csv_to_list_of_dict": "00_core.ipynb",
         "percent_gain": "01_financial.ipynb"}

modules = ["core.py",
           "financial.py"]

doc_url = "https://adammenges.github.io/adampy/"

git_url = "https://github.com/adammenges/adampy/tree/master/"

def custom_doc_links(name): return None
