# AUTOGENERATED! DO NOT EDIT! File to edit: 01_financial.ipynb (unless otherwise specified).

__all__ = ['percent_gain']

# Cell
def percent_gain(start, end):
    "Calculate a percentage gain, aka: ((NP-OP)/OP)*100 = PG"
    return ((float(end)-float(start))/float(start))*100